FROM icfpcontest2020/python

COPY docker/with_the_same_user.sh /install/with_the_same_user.sh


RUN apt-get update --fix-missing && \
    apt-get install -y sudo


RUN pip3 install --upgrade pip && \
    pip3 install hypothesis pytest ipdb pyls pyls-mypy mypy pytest-mypy

RUN echo 'export PATH=/solution/.nix_docker_inject.env/bin:$PATH' >>/etc/profile
RUN echo 'export PYTHONPATH=/solution/src:$PYTHONPATH' >>/etc/profile
RUN echo 'export SOLUTION_SOURCE=/solution' >>/etc/profile
RUN echo 'alias ipython=/solution/ipython.sh' >>/etc/profile

RUN pip3 install --upgrade pip && \
    pip3 install dateutils
