# coding: utf-8

# flake8: noqa
"""
    ICFP Contest 2020 API

    See <a href='https://github.com/icfpcontest2020/aliens-proxy-protocol' target='_blank'>https://github.com/icfpcontest2020/aliens-proxy-protocol<a/>  # noqa: E501

    The version of the OpenAPI document: v1
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

# import models into model package
from openapi_client.models.build_system_registration_info_dto import BuildSystemRegistrationInfoDto
from openapi_client.models.build_system_registration_status import BuildSystemRegistrationStatus
from openapi_client.models.lightning_scoreboard_dto import LightningScoreboardDto
from openapi_client.models.problem_description_dto import ProblemDescriptionDto
from openapi_client.models.problem_dto import ProblemDto
from openapi_client.models.registered_team_dto import RegisteredTeamDto
from openapi_client.models.submission_dto import SubmissionDto
from openapi_client.models.submission_status import SubmissionStatus
from openapi_client.models.team_dto import TeamDto
from openapi_client.models.team_for_problems_scoreboard_dto import TeamForProblemsScoreboardDto
